clears_per_week = 2
num_samples = 100000
num_extra_vault_items = 3

[trading_rule]
source = "Always"
target = "MostPieces"

[members]
Eisenpelz = "Monk"
Vaelldur = "Monk"
Tendronas = "Monk"
Wings = "Monk"
Rav = "Monk"
Nanuss = "Monk"
Atela = "Monk"
Altenna = "Monk"
Nosimage = "Monk"
Zuko = "Monk"
Divisive = "Monk"
Jop = "Monk"
Flemingo = "Monk"
Kim = "Monk"
Heiji = "Monk"
Ivan = "Monk"
Kap = "Monk"
Traltixx = "Monk"
Gucci = "Monk"
Mesprit = "Monk"
Sokchoy = "Monk"
Kadmix = "Monk"
Maelz = "Monk"
Velium = "Monk"
Keegan = "Monk"
